homeassistant:

###############################################################################
#                                                                             #
#                           C U S T O M I Z E                                 #
#                                                                             #
###############################################################################   
###############################################################################
#                                                                             #
#                         S C R I P T S                                       #
#                                                                             #
###############################################################################      

###############################################################################
#                                                                             #
#                         S W I T C H  S O N O F F                            #
#                                                                             #
###############################################################################  
###############################################################################
#                                                                             #
#                           A U T O M A Ç Õ E S                               #
#                                                                             #
###############################################################################   
automation:

  - alias: Ligar luz
    initial_state: true
    trigger:
      - platform: time
        at: '19:00:00'     #aqui escolhes a hora a que eres que acenda
    action:
      - service: switch.turn_on
        entity_id: switch.oteushelly

  - alias: Desligar Luz
    initial_state: true
    trigger:
    - platform: time
      at: '22:00:00'     #aqui é a hora a que queres que desligue
    action:
      - service: switch.turn_off
        entity_id: switch.oteushelly